### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by dukedegen**

### CODE REVIEW

**Comment by tikisailor** [comment]
Should we add a link to the user docs too? https://docs.bankless.community/mad-hatter-product-support/

**Comment by dukedegen** [comment]
> Should we add a link to the user docs too? https://docs.bankless.community/mad-hatter-product-support/

Added link to user docs.

**Review by nonsensecodes — APPROVED** [review]
This is excellent. Thank you for reworking these docs, @dukedegen!

**Review by amaredeus — APPROVED** [review]
Good man!

**Pull request merged**
